# Generated by Django 5.0.6 on 2024-11-01 13:05

import auctions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bids",
            options={"verbose_name": "Bids", "verbose_name_plural": "Bids"},
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={"verbose_name": "Comments", "verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="listings",
            options={"verbose_name": "Listings", "verbose_name_plural": "Listings"},
        ),
        migrations.AlterModelOptions(
            name="winners",
            options={"verbose_name": "Winners", "verbose_name_plural": "Winners"},
        ),
        migrations.AlterField(
            model_name="listings",
            name="user",
            field=models.ForeignKey(
                default=auctions.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
